# Generated by Django 2.2.7 on 2020-05-31 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0007_auto_20200411_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='post_pics'),
        ),
    ]
